### ISSUE TITLE
como instalar

### ISSUE THREAD

**Issue by wubuyun** [JMultimidia/ecommerce#1]
como instala e o login?

**Comment by JMultimidia** [comment]
Faz parte de um curso ainda em andamento.

 

De: wubuyun [mailto:notifications@github.com] 
Enviada em: terça-feira, 17 de abril de 2018 23:55
Para: JMultimidia/ecommerce <ecommerce@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [JMultimidia/ecommerce] como instalar (#1)

 

como instala e o login?

**Comment by wubuyun** [comment]
ok, aguardo..
